version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pir-api
    container_name: pir-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
      # 以下环境变量需要在运行时提供或通过环境文件加载
      - MONGODB_URI=${MONGODB_URI}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - AUTH_TOKEN=${AUTH_TOKEN}
    env_file:
      - .env
    networks:
      - pir-network

networks:
  pir-network:
    driver: bridge